-- MySQL Script generated by MySQL Workbench
-- Thu Apr 22 12:07:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema thunder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema thunder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `thunder` DEFAULT CHARACTER SET utf8 ;
USE `thunder` ;

-- -----------------------------------------------------
-- Table `thunder`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thunder`.`user` (
  `user_uid` INT NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(40) NOT NULL,
  `user_passwd` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `user_town` VARCHAR(45) NOT NULL,
  `user_phone` VARCHAR(14) NOT NULL,
  `user_gender` CHAR(1) NOT NULL,
  `user_date` TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (`user_uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thunder`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thunder`.`category` (
  `cat_id` INT NOT NULL,
  `cat_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thunder`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thunder`.`product` (
  `pd_id` INT NOT NULL AUTO_INCREMENT,
  `pd_title` VARCHAR(50) NOT NULL,
  `pd_price` INT NOT NULL,
  `pd_contents` TEXT NOT NULL,
  `pd_deliver` VARCHAR(20) NOT NULL,
  `pd_status` VARCHAR(10) NOT NULL,
  `pd_color` VARCHAR(20) NOT NULL,
  `pd_washing` VARCHAR(20) NOT NULL,
  `pd_size` VARCHAR(20) NOT NULL,
  `pd_date` TIMESTAMP DEFAULT NOW()
  `user_uid` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`pd_id`),
  INDEX `fk_product_user1_idx` (`user_uid` ASC) VISIBLE,
  INDEX `fk_product_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_user1`
    FOREIGN KEY (`user_uid`)
    REFERENCES `thunder`.`user` (`user_uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `thunder`.`category` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thunder`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thunder`.`image` (
  `img_id` INT NOT NULL,
  `pd_id` INT NOT NULL,
  `img_url` VARCHAR(150) NOT NULL,
  `img_type` VARCHAR(45) NOT NULL,
  `img_size` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`img_id`, `pd_id`),
  INDEX `fk_image_product_idx` (`pd_id` ASC) VISIBLE,
  CONSTRAINT `fk_image_product`
    FOREIGN KEY (`pd_id`)
    REFERENCES `thunder`.`product` (`pd_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
